#!/bin/bash
set -e

if [ -d "/c/Ultibo/Core" ]; then
	LAZDIR=/c/Ultibo/Core
fi

if [ -d "$HOME/ultibo/core" ]; then
	LAZDIR="$HOME/ultibo/core"
fi

LPINAME=fipq
MODES="QEMUVPB RPI RPI2 RPI3"

function buildmode {
    MODE=$1
    echo $MODE
    rm -rf lib/
    WD=$(pwd)
    pushd $LAZDIR >& /dev/null
    ./lazbuild --build-mode=BUILD_MODE_$MODE $WD/$LPINAME.lpi
    popd >& /dev/null
    mv kernel* $LPINAME-kernel-${MODE,,}.img
}

rm -rf *kernel*.img kernel.bin
for MODE in $MODES
do
    buildmode $MODE
done
