#!/bin/bash
set -e

# stop all subprocesses at exit
function finish {
  PGID=$(ps -o pgid= $$ | grep -o [0-9]*)
  setsid kill -- -$PGID
  exit 0
}
trap finish EXIT

apt-get update
apt-get -y dist-upgrade
if [[ -e /var/run/reboot-required ]]
then
    reboot
fi
apt-get -y install fail2ban ufw qemu-system-arm

ufw allow 5790 # websocket vnc
ufw allow 5823 # telnet
ufw allow 5990 # classic vnc

echo starting qemu ...
qemu-system-arm \
    -machine versatilepb -cpu cortex-a8 -m 256M \
    -drive file=ultimc-qemu-sd-fat12.img,if=sd,format=raw \
    -kernel fipq-kernel-qemuvpb.img \
    -display none \
    -vnc :90,websocket=5790 \
    -net nic -net user,hostfwd=tcp::5823-:23 \
    -append "NETWORK0_IP_CONFIG=STATIC NETWORK0_IP_ADDRESS=10.0.2.15 NETWORK0_IP_NETMASK=255.255.255.0 NETWORK0_IP_GATEWAY=10.0.2.2"  \
    \
    |& egrep -v '^(ALSA |alsa:|audio:|pulseaudio:)'
